/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inven.controller;

import java.util.EventObject;

import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.inven.gui.AdminDashboard;
import com.inven.gui.Login;
import com.inven.models.User;
import com.inven.services.UserServices;
import com.inven.utils.Koneksi;
import com.inven.utils.TableHelper;

/**
 *
 * @author kyra
 */
public class AdminUserController extends javax.swing.JFrame {

    /**
     * Creates new form AnggotaService
     */
    public AdminUserController() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewUser = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        passwd = new javax.swing.JLabel();
        roles = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwdField = new javax.swing.JPasswordField();
        rolesBox = new javax.swing.JComboBox<>();
        newUserButton = new javax.swing.JButton();
        editUserFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        edUsername = new javax.swing.JLabel();
        edPasswd = new javax.swing.JLabel();
        edRoles = new javax.swing.JLabel();
        edUsernameField = new javax.swing.JTextField();
        edPasswdField = new javax.swing.JPasswordField();
        edRolesBox = new javax.swing.JComboBox<>();
        editUserButton = new javax.swing.JButton();
        panelContainer = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jlabel2 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tambahUser = new javax.swing.JButton();
        updateUser = new javax.swing.JButton();
        deleteUser = new javax.swing.JButton();

        addNewUser.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addNewUser.setResizable(false);
        addNewUser.setSize(new java.awt.Dimension(300, 200));

        jPanel1.setBackground(new java.awt.Color(114, 135, 253));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 250));

        username.setFont(new java.awt.Font("NotoSans NF Med", 1, 14)); // NOI18N
        username.setText("Username");

        passwd.setFont(new java.awt.Font("NotoSansM NF Med", 1, 14)); // NOI18N
        passwd.setText("Password");

        roles.setFont(new java.awt.Font("NotoSans NF Med", 1, 14)); // NOI18N
        roles.setText("Roles");

        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameField.setToolTipText("username");

        passwdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        rolesBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        rolesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));

        newUserButton.setBackground(new java.awt.Color(166, 209, 137));
        newUserButton.setFont(new java.awt.Font("JetBrainsMono NF", 1, 14)); // NOI18N
        newUserButton.setText("AddUser");
        newUserButton.setPreferredSize(new java.awt.Dimension(90, 25));
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(newUserButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(username)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(passwd,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(roles,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(passwdField, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rolesBox, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(51, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(username)
                                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwd)
                                        .addComponent(passwdField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(roles)
                                        .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(newUserButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)));

        javax.swing.GroupLayout addNewUserLayout = new javax.swing.GroupLayout(addNewUser.getContentPane());
        addNewUser.getContentPane().setLayout(addNewUserLayout);
        addNewUserLayout.setHorizontalGroup(
                addNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        addNewUserLayout.setVerticalGroup(
                addNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        editUserFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editUserFrame.setSize(new java.awt.Dimension(0, 0));

        jPanel4.setBackground(new java.awt.Color(114, 135, 253));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 250));

        edUsername.setFont(new java.awt.Font("NotoSans NF Med", 1, 14)); // NOI18N
        edUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edUsername.setText("Username");
        edUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        edPasswd.setFont(new java.awt.Font("NotoSansM NF Med", 1, 14)); // NOI18N
        edPasswd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edPasswd.setText("Password");
        edPasswd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        edRoles.setFont(new java.awt.Font("NotoSans NF Med", 1, 14)); // NOI18N
        edRoles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edRoles.setText("Roles");
        edRoles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        edUsernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edUsernameField.setToolTipText("username");

        edPasswdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        edRolesBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        edRolesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));

        editUserButton.setBackground(new java.awt.Color(166, 209, 137));
        editUserButton.setFont(new java.awt.Font("JetBrainsMono NF", 1, 14)); // NOI18N
        editUserButton.setText("Edit User");
        editUserButton.setPreferredSize(new java.awt.Dimension(90, 25));
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(120, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel4Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(edUsername, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edPasswd, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(edPasswdField)
                                                .addComponent(edUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(edRolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(57, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(edUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addComponent(edRolesBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(edPasswdField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(edUsername)
                                                .addGap(18, 18, 18)
                                                .addComponent(edPasswd)
                                                .addGap(18, 18, 18)
                                                .addComponent(edRoles)))
                                .addGap(33, 33, 33)
                                .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)));

        javax.swing.GroupLayout editUserFrameLayout = new javax.swing.GroupLayout(editUserFrame.getContentPane());
        editUserFrame.getContentPane().setLayout(editUserFrameLayout);
        editUserFrameLayout.setHorizontalGroup(
                editUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        editUserFrameLayout.setVerticalGroup(
                editUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(114, 135, 253));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelContainer.setBackground(new java.awt.Color(245, 169, 127));
        panelContainer.setPreferredSize(new java.awt.Dimension(600, 550));

        panelMenu.setBackground(new java.awt.Color(114, 135, 253));

        label1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        label1.setText("  ");

        jlabel2.setFont(new java.awt.Font("NotoSans NF SemBd", 1, 18)); // NOI18N
        jlabel2.setText(new User().getCurrentUser());

        logoutButton.setBackground(new java.awt.Color(210, 15, 57));
        logoutButton.setFont(new java.awt.Font("NotoSans NF", 1, 14)); // NOI18N
        logoutButton.setText("Keluar");
        logoutButton.setToolTipText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(223, 142, 29));
        backButton.setFont(new java.awt.Font("NotoSans NF", 1, 14)); // NOI18N
        backButton.setText("Kembali");
        backButton.setToolTipText("Kembali kemenu utama");
        backButton.setBorderPainted(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                                .addContainerGap(413, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(logoutButton)
                                .addGap(15, 15, 15))
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelMenuLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(307, Short.MAX_VALUE))));
        panelMenuLayout.setVerticalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                                .addContainerGap(35, Short.MAX_VALUE)
                                .addGroup(
                                        panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(logoutButton)
                                                .addComponent(backButton))
                                .addGap(29, 29, 29))
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelMenuLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(panelMenuLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        jPanel2.setBackground(new java.awt.Color(245, 169, 127));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 200));

        jScrollPane1.setBackground(new java.awt.Color(166, 209, 137));

        userTable.setBackground(new java.awt.Color(166, 209, 137));
        userTable.setModel(com.inven.utils.TableHelper.getTableModel());
        userTable.setEditingColumn(0);
        userTable.setEditingRow(0);
        userTable.setShowHorizontalLines(true);
        userTable.setShowVerticalLines(true);
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194,
                                        Short.MAX_VALUE)));

        jPanel3.setBackground(new java.awt.Color(245, 169, 127));

        tambahUser.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        tambahUser.setText("Tambah User");
        tambahUser.setToolTipText("");
        tambahUser.setBorderPainted(false);
        tambahUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahUser.setMaximumSize(new java.awt.Dimension(130, 25));
        tambahUser.setPreferredSize(new java.awt.Dimension(130, 25));
        tambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahUserActionPerformed(evt);
            }
        });

        updateUser.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        updateUser.setText("Update User");
        updateUser.setToolTipText("");
        updateUser.setBorderPainted(false);
        updateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateUser.setMaximumSize(new java.awt.Dimension(130, 25));
        updateUser.setPreferredSize(new java.awt.Dimension(130, 25));
        updateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserActionPerformed(evt);
            }
        });

        deleteUser.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        deleteUser.setText("Delete User");
        deleteUser.setToolTipText("");
        deleteUser.setBorderPainted(false);
        deleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUser.setMaximumSize(new java.awt.Dimension(130, 25));
        deleteUser.setPreferredSize(new java.awt.Dimension(130, 25));
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(tambahUser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(updateUser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tambahUser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(updateUser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(87, Short.MAX_VALUE)));

        javax.swing.GroupLayout panelContainerLayout = new javax.swing.GroupLayout(panelContainer);
        panelContainer.setLayout(panelContainerLayout);
        panelContainerLayout.setHorizontalGroup(
                panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        panelContainerLayout.setVerticalGroup(
                panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelContainerLayout.createSequentialGroup()
                                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 489,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateUserActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // dispose();
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih User yang ingin dirubah terlebih dahulu");
            return;
        }

        editUserFrame.setSize(350, 250);
        editUserFrame.setVisible(true);
        editUserFrame.setLocationRelativeTo(null);

        edUsernameField.setText((String) userTable.getValueAt(selectedRow, 1));
        edPasswdField.setText((String) userTable.getValueAt(selectedRow, 2));
        edRolesBox.setSelectedItem((String) userTable.getValueAt(selectedRow, 3));
    }// GEN-LAST:event_updateUserActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateUserActionPerformed
        // TODO add your handling code here:
        int selectedRow = userTable.getSelectedRow();

        int userId = (int) userTable.getValueAt(selectedRow, 0);
        String username = edUsernameField.getText();
        String passwd = new String(edPasswdField.getPassword());
        String role = (String) edRolesBox.getSelectedItem();

        new UserServices().updateUser(username, passwd, role, userId, this);
    }// GEN-LAST:event_updateUserActionPerformed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteUserActionPerformed
        // TODO add your handling code here:
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih User yang ingin dirubah terlebih dahulu");
            return;
        }

        int userId = (int) userTable.getValueAt(selectedRow, 0);
        new UserServices().deleteUser(userId);
    }// GEN-LAST:event_deleteUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        userTable.getTableHeader().setReorderingAllowed(false);
        userTable.setDefaultEditor(Object.class, new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject anEvent) {
                return false;
            };
        });

        TableHelper.loadTable(false, "users");
    }// GEN-LAST:event_formWindowOpened

    private void tambahUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddUserActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // dispose();
        addNewUser.setSize(350, 250);
        addNewUser.setVisible(true);
        addNewUser.setLocationRelativeTo(null);
    }// GEN-LAST:event_AddUserActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newUserButtonActionPerformed
        // TODO add your handling code here:
        String username = usernameField.getText();
        String passwd = new String(passwdField.getPassword());
        String role = (String) rolesBox.getSelectedItem();

        new UserServices().addNewUser(username, passwd, role, this);

    }// GEN-LAST:event_newUserButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        TableHelper.loadTable(false, "users");
        dispose();
        new AdminDashboard().setVisible(true);
    }// GEN-LAST:event_backButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutButtonActionPerformed
        // TODO: add your handling code here:
        System.out.println(Koneksi.logoutConnection());
        dispose();
        new Login().setVisible(true);
    }// GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUserController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUserController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUserController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUserController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUserController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFrame addNewUser;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteUser;
    private javax.swing.JLabel edPasswd;
    public javax.swing.JPasswordField edPasswdField;
    private javax.swing.JLabel edRoles;
    public javax.swing.JComboBox<String> edRolesBox;
    private javax.swing.JLabel edUsername;
    public javax.swing.JTextField edUsernameField;
    public javax.swing.JButton editUserButton;
    public javax.swing.JFrame editUserFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel2;
    private java.awt.Label label1;
    private javax.swing.JButton logoutButton;
    public javax.swing.JButton newUserButton;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel passwd;
    public javax.swing.JPasswordField passwdField;
    private javax.swing.JLabel roles;
    public javax.swing.JComboBox<String> rolesBox;
    private javax.swing.JButton tambahUser;
    private javax.swing.JButton updateUser;
    public javax.swing.JTable userTable;
    private javax.swing.JLabel username;
    public javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
