/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inven.controller;

import com.inven.gui.*;
import com.inven.models.User;
import com.inven.services.BarangServices;

import java.util.EventObject;

import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.inven.utils.Koneksi;
import com.inven.utils.TableHelper;

/**
 *
 * @author kyra
 */
public class BarangController extends javax.swing.JFrame {

    /**
     * Creates new form UserPanel
     */
    public BarangController() {
        initComponents();
        setLocationRelativeTo(null);
        if (roleUser()) {
            backButton.setVisible(true);
        } else {
            backButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBarang = new javax.swing.JFrame();
        addContainer = new javax.swing.JPanel();
        namaBarang = new javax.swing.JLabel();
        kategoriBarang = new javax.swing.JLabel();
        jumlahBarang = new javax.swing.JLabel();
        keteranganBarang = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        kategoriField = new javax.swing.JTextField();
        jumlahField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        keteranganField = new javax.swing.JTextArea();
        addButtonClick = new javax.swing.JButton();
        editBarang = new javax.swing.JFrame();
        editContainer = new javax.swing.JPanel();
        namaBarang1 = new javax.swing.JLabel();
        kategoriBarang1 = new javax.swing.JLabel();
        jumlahBarang1 = new javax.swing.JLabel();
        keteranganBarang1 = new javax.swing.JLabel();
        editNamaField = new javax.swing.JTextField();
        editKategoriField = new javax.swing.JTextField();
        editJumlahField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        editKeteranganField = new javax.swing.JTextArea();
        editButtonClick = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        logoutButton = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        tambahButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        addBarang.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addContainer.setBackground(new java.awt.Color(114, 135, 253));

        namaBarang.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        namaBarang.setText("Nama Barang");
        namaBarang.setMaximumSize(new java.awt.Dimension(180, 40));
        namaBarang.setPreferredSize(new java.awt.Dimension(180, 40));

        kategoriBarang.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        kategoriBarang.setText("Kategori Barang");
        kategoriBarang.setMaximumSize(new java.awt.Dimension(180, 40));
        kategoriBarang.setPreferredSize(new java.awt.Dimension(180, 40));

        jumlahBarang.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        jumlahBarang.setText("Jumlah Barang");
        jumlahBarang.setInheritsPopupMenu(false);
        jumlahBarang.setMaximumSize(new java.awt.Dimension(180, 40));
        jumlahBarang.setPreferredSize(new java.awt.Dimension(180, 40));

        keteranganBarang.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        keteranganBarang.setText("Keterangan Barang");
        keteranganBarang.setMaximumSize(new java.awt.Dimension(200, 40));
        keteranganBarang.setPreferredSize(new java.awt.Dimension(160, 40));

        namaField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        namaField.setPreferredSize(new java.awt.Dimension(180, 40));

        kategoriField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        kategoriField.setPreferredSize(new java.awt.Dimension(180, 40));

        jumlahField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        jumlahField.setPreferredSize(new java.awt.Dimension(180, 40));

        keteranganField.setColumns(20);
        keteranganField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        keteranganField.setRows(5);
        jScrollPane2.setViewportView(keteranganField);

        addButtonClick.setBackground(new java.awt.Color(166, 209, 137));
        addButtonClick.setFont(new java.awt.Font("JetBrainsMono NF SemiBold", 1, 18)); // NOI18N
        addButtonClick.setText("Tambah");
        addButtonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addContainerLayout = new javax.swing.GroupLayout(addContainer);
        addContainer.setLayout(addContainerLayout);
        addContainerLayout.setHorizontalGroup(
                addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addContainerLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(addContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(keteranganBarang, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140,
                                        Short.MAX_VALUE)
                                .addGroup(addContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(namaField, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kategoriField, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlahField, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                        .addGroup(addContainerLayout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(addButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        addContainerLayout.setVerticalGroup(
                addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addContainerLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(addContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(addContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(kategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kategoriField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(addContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(addContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(keteranganBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28,
                                        Short.MAX_VALUE)
                                .addComponent(addButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout addBarangLayout = new javax.swing.GroupLayout(addBarang.getContentPane());
        addBarang.getContentPane().setLayout(addBarangLayout);
        addBarangLayout.setHorizontalGroup(
                addBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 600, Short.MAX_VALUE)
                        .addGroup(addBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                        addBarangLayout.createSequentialGroup()
                                                .addGap(0, 0, 0)
                                                .addComponent(addContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0))));
        addBarangLayout.setVerticalGroup(
                addBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(addBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                        addBarangLayout.createSequentialGroup()
                                                .addGap(0, 0, 0)
                                                .addComponent(addContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0))));

        editBarang.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editContainer.setBackground(new java.awt.Color(114, 135, 253));

        namaBarang1.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        namaBarang1.setText("Nama Barang");
        namaBarang1.setMaximumSize(new java.awt.Dimension(180, 40));
        namaBarang1.setPreferredSize(new java.awt.Dimension(180, 40));

        kategoriBarang1.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        kategoriBarang1.setText("Kategori Barang");
        kategoriBarang1.setMaximumSize(new java.awt.Dimension(180, 40));
        kategoriBarang1.setPreferredSize(new java.awt.Dimension(180, 40));

        jumlahBarang1.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        jumlahBarang1.setText("Jumlah Barang");
        jumlahBarang1.setInheritsPopupMenu(false);
        jumlahBarang1.setMaximumSize(new java.awt.Dimension(180, 40));
        jumlahBarang1.setPreferredSize(new java.awt.Dimension(180, 40));

        keteranganBarang1.setFont(new java.awt.Font("NotoSans NF", 1, 18)); // NOI18N
        keteranganBarang1.setText("Keterangan Barang");
        keteranganBarang1.setMaximumSize(new java.awt.Dimension(200, 40));
        keteranganBarang1.setPreferredSize(new java.awt.Dimension(160, 40));

        editNamaField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        editNamaField.setPreferredSize(new java.awt.Dimension(180, 40));

        editKategoriField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        editKategoriField.setPreferredSize(new java.awt.Dimension(180, 40));

        editJumlahField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        editJumlahField.setPreferredSize(new java.awt.Dimension(180, 40));

        editKeteranganField.setColumns(20);
        editKeteranganField.setFont(new java.awt.Font("NotoSans NF", 0, 14)); // NOI18N
        editKeteranganField.setRows(5);
        jScrollPane3.setViewportView(editKeteranganField);

        editButtonClick.setBackground(new java.awt.Color(166, 209, 137));
        editButtonClick.setFont(new java.awt.Font("JetBrainsMono NF SemiBold", 1, 18)); // NOI18N
        editButtonClick.setText("Tambah");
        editButtonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editContainerLayout = new javax.swing.GroupLayout(editContainer);
        editContainer.setLayout(editContainerLayout);
        editContainerLayout.setHorizontalGroup(
                editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editContainerLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(editContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(keteranganBarang1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kategoriBarang1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlahBarang1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140,
                                        Short.MAX_VALUE)
                                .addGroup(editContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(editNamaField, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editKategoriField, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editJumlahField, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                        .addGroup(editContainerLayout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(editButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        editContainerLayout.setVerticalGroup(
                editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editContainerLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(editContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(namaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editNamaField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(editContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(kategoriBarang1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editKategoriField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(editContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jumlahBarang1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editJumlahField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(editContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(keteranganBarang1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15,
                                        Short.MAX_VALUE)
                                .addComponent(editButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout editBarangLayout = new javax.swing.GroupLayout(editBarang.getContentPane());
        editBarang.getContentPane().setLayout(editBarangLayout);
        editBarangLayout.setHorizontalGroup(
                editBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(editBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editBarangLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(editContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
        editBarangLayout.setVerticalGroup(
                editBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                        .addGroup(editBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editBarangLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(editContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(114, 135, 253));

        jScrollPane1.setBackground(new java.awt.Color(166, 209, 137));

        userTable.setBackground(new java.awt.Color(166, 209, 137));
        userTable.setModel(TableHelper.getTableModel());
        userTable.setEditingColumn(0);
        userTable.setEditingRow(0);
        userTable.setShowHorizontalLines(true);
        userTable.setShowVerticalLines(true);
        jScrollPane1.setViewportView(userTable);

        jPanel2.setBackground(new java.awt.Color(114, 135, 253));

        label1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        label1.setText(" ");

        logoutButton.setBackground(new java.awt.Color(210, 15, 57));
        logoutButton.setFont(new java.awt.Font("NotoSans NF", 1, 14)); // NOI18N
        logoutButton.setText("Keluar");
        logoutButton.setBorderPainted(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setMaximumSize(new java.awt.Dimension(90, 25));
        logoutButton.setPreferredSize(new java.awt.Dimension(90, 25));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("NotoSans NF SemBd", 1, 18)); // NOI18N
        username.setText(new User().getCurrentUser());

        tambahButton.setFont(new java.awt.Font("JetBrainsMono NF", 1, 14)); // NOI18N
        tambahButton.setText("Tambah");
        tambahButton.setMaximumSize(new java.awt.Dimension(85, 26));
        tambahButton.setPreferredSize(new java.awt.Dimension(85, 25));
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("JetBrainsMono NF", 1, 14)); // NOI18N
        editButton.setText("Edit");
        editButton.setMaximumSize(new java.awt.Dimension(85, 26));
        editButton.setPreferredSize(new java.awt.Dimension(85, 25));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("JetBrainsMono NF", 1, 14)); // NOI18N
        deleteButton.setText("Hapus");
        deleteButton.setMaximumSize(new java.awt.Dimension(85, 26));
        deleteButton.setPreferredSize(new java.awt.Dimension(85, 25));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(223, 142, 29));
        backButton.setFont(new java.awt.Font("NotoSans NF", 1, 14)); // NOI18N
        backButton.setText("Kembali");
        backButton.setMaximumSize(new java.awt.Dimension(90, 26));
        backButton.setPreferredSize(new java.awt.Dimension(90, 25));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 230,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(224, 224, 224)
                                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(username)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(logoutButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(backButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tambahButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26,
                                                Short.MAX_VALUE)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        TableHelper.loadTable(true, "barang");
        dispose();
        new AdminDashboard().setVisible(true);
    }// GEN-LAST:event_backButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        addBarang.setSize(600, 400);
        addBarang.setVisible(true);
        addBarang.setLocationRelativeTo(null);
    }// GEN-LAST:event_tambahButtonActionPerformed

    private void addButtonClickActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonClick1ActionPerformed
        // TODO add your handling code here:
        String namaBarang = namaField.getText();
        String kategoriBarang = kategoriField.getText();
        String jumlahBarang = jumlahField.getText();
        String keteranganBarang = keteranganField.getText();

        new BarangServices().tambahBarang(roleUser(), namaBarang, kategoriBarang, jumlahBarang, keteranganBarang, this);

        namaField.setText("");
        kategoriField.setText("");
        jumlahField.setText("");
        keteranganField.setText("");
    }// GEN-LAST:event_buttonClick1ActionPerformed

    private void editButtonClickActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonClickActionPerformed
        // TODO add your handling code here:
        int selectedRow = userTable.getSelectedRow();

        int barangId = (int) userTable.getValueAt(selectedRow, 0);
        String namaBarang = editNamaField.getText();
        String kategoriBarang = editKategoriField.getText();
        String jumlahBarang = editJumlahField.getText();
        String keteranganBarang = editKeteranganField.getText();

        new BarangServices().editBarang(roleUser(), namaBarang, kategoriBarang, jumlahBarang, keteranganBarang,
                barangId,
                this);
    }// GEN-LAST:event_buttonClickActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih User yang ingin dirubah terlebih dahulu");
            return;
        }

        editBarang.setSize(600, 400);
        editBarang.setVisible(true);
        editBarang.setLocationRelativeTo(null);

        editNamaField.setText((String) userTable.getValueAt(selectedRow, 1));
        editKategoriField.setText((String) userTable.getValueAt(selectedRow, 2));
        editJumlahField.setText((String) userTable.getValueAt(selectedRow, 3));
        editKeteranganField.setText((String) userTable.getValueAt(selectedRow, 5));
    }// GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih User yang ingin dirubah terlebih dahulu");
            return;
        }

        int barangId = (int) userTable.getValueAt(selectedRow, 0);
        new BarangServices().hapusBarang(roleUser(), barangId);
    }// GEN-LAST:event_deleteButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(Koneksi.logoutConnection());
        dispose();
        new Login().setVisible(true);
    }// GEN-LAST:event_logoutButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        userTable.getTableHeader().setReorderingAllowed(false);
        userTable.setDefaultEditor(Object.class, new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject anEvent) {
                return false;
            };
        });

        TableHelper.loadTable(true, "barang");
    }// GEN-LAST:event_formWindowOpened

    private boolean roleUser() {
        boolean isAdmin;
        if (User.getRoleUser() == "admin") {
            isAdmin = true;
        } else {
            isAdmin = false;
        }
        return isAdmin;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangController.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFrame addBarang;
    public javax.swing.JButton addButtonClick;
    public javax.swing.JPanel addContainer;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    public javax.swing.JFrame editBarang;
    private javax.swing.JButton editButton;
    public javax.swing.JButton editButtonClick;
    public javax.swing.JPanel editContainer;
    public javax.swing.JTextField editJumlahField;
    public javax.swing.JTextField editKategoriField;
    public javax.swing.JTextArea editKeteranganField;
    public javax.swing.JTextField editNamaField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jumlahBarang;
    private javax.swing.JLabel jumlahBarang1;
    public javax.swing.JTextField jumlahField;
    private javax.swing.JLabel kategoriBarang;
    private javax.swing.JLabel kategoriBarang1;
    public javax.swing.JTextField kategoriField;
    private javax.swing.JLabel keteranganBarang;
    private javax.swing.JLabel keteranganBarang1;
    public javax.swing.JTextArea keteranganField;
    private java.awt.Label label1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel namaBarang;
    private javax.swing.JLabel namaBarang1;
    public javax.swing.JTextField namaField;
    private javax.swing.JButton tambahButton;
    public javax.swing.JTable userTable;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
